### ISSUE TITLE
Not working on Android browser

### ISSUE THREAD

**Issue by jotarun** [fooplugins/FooTable#1]
It seems like the event is not triggered

---

Test platform: Android 2.2 / Webkit 3.1

**Comment by bradvin** [comment]
thanks for letting me know - I will check it out

**Comment by bradvin** [comment]
This has been fixed. Turned out that webkit on android did not like using a variable named "class" so I renamed it to className and all is good. I had issues with the file still being cached on my android emulator, so I made a copy of the live demo at http://themergency.com/footable-demo/test/demo2.htm just to make sure it was working correctly
