### ISSUE TITLE
Column width issue

### ISSUE THREAD

**Issue by ruffeo** [fooplugins/FooTable#104]
I hope someone has an easy answer to this, but I can't figure out how to set the column width for the table. 

![capture](https://f.cloud.github.com/assets/896852/814935/471ef642-ef1f-11e2-8792-84699b75c919.JPG)

**Comment by bgil** [comment]
Found a solution!

Define your column header with a spacer:
&lt;th data-hide="phone" >Header Text
&lt;span class="fooTableSpacer">________________________&lt;/span>
&lt;/th>

Then define the fooTableSpacer css to make the text disappear

.fooTableSpacer {
    color:rgba(0,0,0,0);
    background-color: rgba(0,0,0,0);
    text-shadow: none;
}

**Comment by bgil** [comment]
Found a problem with my solution above.... all of those underscores appear in the details when the column is hidden.
So, we need to adjust the footable.js file.  In the method 

ft.createOrUpdateDetailRow = function(actualRow) {

just before
                values.push({
                    'name' : name,
                    'value' : ft.parse(this, column),
                    'display' : $.trim($(this).html()),
                    'group' : column.group,
                    'groupName' : column.groupName
                });

insert
                if (name.indexOf('__') != -1) {
                    name = name.replace(/_+/g, '');
                }

I am the first to agree this fix is a kludge. Anyone have a better suggestion?

**Comment by mspanish** [comment]
Set the width of your content TD, then the header will adjust to fit that. For example:

  <td class="bigTitle">{resolved_title}</td>

**Comment by steveush** [comment]
Hi,

This is more to do with table styling and CSS rather than FooTable so I'm closing this as  an issue.

Thanks
Steve

**Comment by jacobrien** [comment]
I don't believe this is an issue with the css. Unless footable is manipulating the css for the table header width. I have put a set timeout on the footable init of 6 seconds. On page load, the table header widths are fine. Once I init footable, the widths are not rendered.

```
<thead>
  <tr>
    <th data-type="html" style="width:50px;"></th>
    <th style="width:50%;text-align:center;">Priority</th>
    <th style="width:60px;text-align:center;">ID</th>
    <th style="width:250px;">Agency</th>
    <th style="width:250px">Description</th>
    <th style="width:250px">Transcode Targets</th>
    <th style="width:150px">Supplier</th> 
    <th data-type="html" style="width:50px"></td>
  </tr>     
</thead>
```

Ive tried using percentages, and css classes with no luck.

**Comment by steveush** [comment]
@jobrient3media When this issue was initially created 3 years ago there was no bug and this was purely a CSS table styling issue. Ironically there has recently been a bug introduced recently and only just reported in #555 which reported CSS classes not being properly pulled across into the column headers, this issue also applies to styles not being applied as well which is what I believe you are seeing. An easy way to test is to insert the following code into your page just below main FooTable JS file:

``` javascript
<script>
    FooTable.Column.extend('$create', function(){
        this._super();
        this.$el.addClass(this.classes.join(' ')).css(this.style);
    });
</script>
```

This should modify the method that creates the column headers and properly appends parsed classes and styles to them.

Let me know if this resolves your issue as I am going to be adding that fix into the develop branch for the next release.

Thanks

**Comment by jacobrien** [comment]
Perfect! Thank you.
