### ISSUE TITLE
footable and xeditable

### ISSUE THREAD

**Issue by hugsbrugs** [fooplugins/FooTable#156]
Hello,

thanks for this awsome plugin ! 
I've had a problem I resolved almost easily (http://stackoverflow.com/questions/19591928/footable-in-bootstrap-3-not-initializing), I'm now going further in footable use cause I want to do inline editing with the excellent x-editable plugin.

It works perfectly for data not hidden but not for hidden data revealed on + click.

It seems click on those data is disabled ? how could I re-enabled it ?

Thanks to all the team !

Hugo

**Comment by judebowman** [comment]
I have this same issue.  Did you ever find a resolution?

**Comment by bradvin** [comment]
Not yet. At the moment, FooTable clones the table cell contents when creating the detail rows. This works fine for display-only data, but it falls short when using form input fields. You end up with duplicate fields and the state is not carried across.

Instead of cloning, the cell contents need to be moved. Placeholders also need to be created so that FooTable can figure out where to move the elements back when the table is made larger again.

This is top priority in the V3 rewrite

**Comment by judebowman** [comment]
Yes, I am having issues with state with the x-editable field is updated and the column goes from hidden to full view.

Any idea when v3 is scheduled for release?

**Comment by bradvin** [comment]
have not started on it yet. I am hoping it will be done by end of june

**Comment by judebowman** [comment]
Good luck!

**Comment by minroo** [comment]
Thanks for the awesome FooTable. Made few changes and added the documentation to make it work for form Input fields. I believe it will also handle the dynamic column data
https://github.com/bradvin/FooTable/pull/285
