### ISSUE TITLE
Bootstrap table stripe negated

### ISSUE THREAD

**Issue by Relequestual** [fooplugins/FooTable#162]
When using bootstrap, a table with the class of table-stripe creates a striped table.

When expending a row, a new row is created. When the row is collapsed, the row is still present but hidden.

This causes the striping of rows to be off.

Obviously it isn't mission critical, but still a bug.

Maybe a possible solution would be to store the hidden row in a temporary table if the table-stripped class is on the table, and return it when row is expanded again?

**Comment by bradvin** [comment]
The problem with table striping in bootstrap is that it is done via CSS. 
This CSS solution will fall apart with FooTable, because FooTable appends rows to the table which you expand and collapse. Unfortunately, this can never be fixed, but there is a javascript solution which you can check out:

https://github.com/bradvin/FooTable/blob/V2/js/footable.striping.js
