### ISSUE TITLE
Performance in IE with tables > 70 rows

### ISSUE THREAD

**Issue by uklajo** [fooplugins/FooTable#206]
Hello,
when I try to display more than (about) 70  rows in a table the IE (9,10,11) break up loading and is asking if the script should be executed furthermore.

Chrome +  FF make no problems.

(I know - do not use IE :-) ... but we have to support IE :-()

Is there a solution for this performance issue?

**Comment by Zambonilli** [comment]
Seeing the same thing with IE7 and ~75 records.  It hangs to the point where IE asks to kill the script.

**Comment by Zambonilli** [comment]
This looks to be caused by the ft.render method doing an expensive (~500ms/iteration) jquery select for each row in the table.  footable.js line 613

selector += ', > thead > tr[data-group-row="true"] > th[data-group="' + data.group + '"]';

**Comment by bradvin** [comment]
hey guys,

Testing with IE11 (changing to IE9 and IE10 via the IE dev tools)

I tested with 200 rows and it seemed fine in "IE9". Not as fast as chrome, but it was usable. I then tested 1000 rows and things got bad!

@Zambonilli even with that line completely removed, there was no impact on the performance

**Comment by Zambonilli** [comment]
Sorry, I wasn't very clear in my previous post.  It's the execution of the find with the selector that is slow (~500ms/iteration).   However, in further profiling it looks like even the logic to build the selector query each iteration is slow.

I was able to drastically reduce the redraw method's execution time by short circuiting all of the query building and executing if the column wasn't being hidden.  This causes columns to not reappear if the user shrinks the screen and expands it but that seems like a good tradeoff.

Doing that got 75 records to load better in IE7 but still prompt with the warning about a hanging script.  Since we're not using any features other than sorting, commenting out the jquery finds for grouping, detail and footer brought the execution down a lot more.

We went from ~25-30 seconds constructor time in IE7 to < 2 seconds by just reworking the redraw method.  Maybe adding fields on the configuration that indicate if a feature is used would allow for the short circuiting better.

**Comment by Zambonilli** [comment]
here's a gist of what we did.  https://gist.github.com/Zambonilli/9608773

**Comment by Zambonilli** [comment]
When trying to construct a footable with 225 records even with the gist above it was raising the hanging js prompt.  So we switched over to detecting if the browser is less than IE9 and then just returning from the redraw method.  It's a cleaner fix than the other gist but still not as ideal as having feature Enabled flags.  

https://gist.github.com/Zambonilli/9610278
