### ISSUE TITLE
IE8 Script Error

### ISSUE THREAD

**Issue by dvdorchard** [fooplugins/FooTable#226]
Hello to all the much smarter people than I, 

I have footable installed on a page that I am testing - see http://www.dvdorchard.com.au/blu-ray-boxsets1.asp?I=False.  Works perfectly...except in IE8 where the browser throws one of those Script responding slowly errors, and I have to agree to stop the script running.

The console then shows an Operation Aborted entry on various different lines and characters in 1.9.1/jquery.min.js - line 2 char 11881 or line 4 char 10144, and others etc.

I removed a number of other scripts from this page and I'm fairly sure the issue is occurring when footable is loading (and it wasn't an issue before I added footable script) - after you stop the script everything loads except the bar at the right, and footable doesn't work - when you shrink the page it doesn't change etc - see it in another browser to understand it better than I can explain it in writing !!

Can anyone help please ?

**Comment by developerchick** [comment]
_raises hand_ 
I have this issue too.

**Comment by dvdorchard** [comment]
Hi developerchick

I've given up trying to solve it, got the error on another page today.  

Because (in my world) the whole responsive table scenario is really for mobile viewing, which I presume will NOT be with an IE8 browser, I simply don't include or add the script unless it's a mobile browser.  I did leave the CSS files in however so it looks the same.

**Comment by developerchick** [comment]
I found a solution: http://responsivenews.co.uk/post/18948466399/cutting-the-mustard

Detect for features (HTML 4 or HTML 5) using this:
if('querySelector' in document
     && 'localStorage' in window
     && 'addEventListener' in window) {
     // bootstrap the javascript application. I stuck my foo table code in here and it worked.
     }

Oh...and by worked I mean that I no longer get the long running script error. The foo table doesn't work in IE8, but I'm not concerned about that since like you said- no mobile browser is running IE8.

Hope this helps!

**Comment by bradvin** [comment]
@dvdorchard you are right about not worrying about IE8 for mobile, so not including it for IE8 is a clever workaround.

@developerchick thanks for your snippet.

We are busy rewriting FooTable from the ground up as we speak, so I will make sure this issue is fixed in a new milestone.

thanks for supporting FooTable :)

**Comment by developerchick** [comment]
Thank you bradvin for providing this resource!

**Comment by ghost** [comment]
Hello, 

Was this issue ever resolved? I am facing the same challenge in IE8, with the Script running too long. Also, I cannot drop IE 8 support.

**Comment by developerchick** [comment]
@singhumd To keep from getting the script running too long error, I use this bit of script at the bottom of pages with a footable:

```
        <script>
            if ('querySelector' in document
             && 'localStorage' in window
             && 'addEventListener' in window) {
                // bootstrap the javascript application
                // ignore if HTML4 (no localStorage). Run the foo table if HTML5.
                $(function () {
                    $('table').footable();
                });
                $('table').bind('footable_breakpoint', function () {
                    $('table').trigger('footable_expand_first_row');
                });
            }
        </script>
```

Hope that helps!
