### ISSUE TITLE
Striping After Filtering Enhancement

### ISSUE THREAD

**Issue by x68507** [fooplugins/FooTable#239]
The current code for adding the striping.even and striping.odd classes attaches a permanent class to a row based on it's index number (rowIndex % 2 === 0) rather than on it's visibility, so this doesn't work when you have filtering AND striping.  I would suggest changing the p.setupStriping function in the footable.striping.js file to the following:

 p.setupStriping = function (ft) {
        $('tbody tr',ft.table).removeClass(ft.options.classes.striping.even).removeClass(ft.options.classes.striping.odd);
        $('tbody tr:visible:even',ft.table).addClass(ft.options.classes.striping.even)
        $('tbody tr:visible:odd',ft.table).addClass(ft.options.classes.striping.odd)
    };

This assigns the striping.even and striping.odd classes based on visibility, not on index.

**Comment by leoarce** [comment]
didn't really need to rewrite the function, just adding or removing :visible on the original function works.  the issue is that not all 3 can work at same time...pagination, striping, and filtering.  with :visible, filtering and striping works (but not pagination and striping).  without :visible, pagination and striping works (but not filtering and striping).
