### ISSUE TITLE
Using tabs with a Foo in each 

### ISSUE THREAD

**Issue by donluz** [fooplugins/FooTable#249]
I have several tabs and each has a footable.  Whatever tab is showing when the page initially loads, the footable hides the columns as intended based on the screen (browser) size.

However switching to another tab shows the table NOT hiding its columns as intended.  Staying on that table and doing a page re-load corrects that tabs footable, but switching to the original tab... same story, rinse/repeat.

There's likely a way to call a "redraw" upon a tab switch??? but I have no idea how to do that.

TIA for any assistance!

**Comment by bradvin** [comment]
this other comment may be able to help out : https://github.com/bradvin/FooTable/issues/28#issuecomment-13311129

**Comment by donluz** [comment]
I checked that out, but couldn't get it to work.  However, I've moved on... somewhat... I found a solution which actually uses Footable's functionality, but within that of "dataTables".  dataTables is a really nice table for... data I found out.  Combining Footable's approach to responsive tables makes it an awesome solution!  Here it is:  https://github.com/Comanche/datatables-responsive

**Comment by rickmills** [comment]
We're having this issue with Bootstrap 3 tabs.

If you put a footable with several columns into a tabbed piece of content, then set a couple of them to data-hide="all" you'll be able to replicate the issue. On first load, all columns are shown. Only when you resize does footable kick in and start working. It means your layout breaks if you load up a table with a lot of columns on a mobile view, inside a tab.

As an example, this is how a tabbed-page looks on a fresh-load inside a tabbed div:
![first load - mobile view broken footable](https://cloud.githubusercontent.com/assets/103707/3843773/fce47990-1e42-11e4-9b1e-b5298761f397.png)

And this is how it looks if I then resize the window, and bring it back down again:
![resized - mobile view broken footable](https://cloud.githubusercontent.com/assets/103707/3843774/fcedf646-1e42-11e4-83e6-5045508c0a92.png)

Obviously the second screenshot is how it's supposed to look all the time.

If I move the table outside of a bootstrap controlled tab area, it renders correctly. The bug seems to be that footable doesn't know it's supposed to be resizing the table when it's hidden from view.

**This issue should be re-opened as it's not resolved, especially if the resolution was to switch to another system.**

**Comment by bradvin** [comment]
The problem with resizing a hidden table is that it's width is considered zero by the plugin, so all you need to do is hook into the changedTab event (or similar) and force footable's resize when it is made visible.
