### ISSUE TITLE
Target the row

### ISSUE THREAD

**Issue by ggeiger** [fooplugins/FooTable#25]
I'm using ajax to delete the row (from my database and from the screen). I'm targeting the table row using:

```
var tablerow = $(this).parents("tr");
```

Once footable kicks in, it creates 2 table rows for each original row, and I can no longer target the original row this way. Any ideas how I can get this working?

Here is the full script:

```
$('.delete-event').click(function(){
// set the vars
var tablerow = $(this).parents("tr");           
var id = $(this).attr("id");            
var string = 'id='+ id ;

// post the filename to the delete page
$.ajax({
    type: "POST",
    url: "delete-event.php",
    data: string,
    cache: false,
    success: function(){
                tablerow.css("background", "red");
                tablerow.fadeOut(function() {
                    $(this).remove();
                });
    }
});
return false;
});
```

**Comment by steveush** [comment]
Hi ggeiger,

Could you show me what your table head looks like and where do you have your delete button placed?

The only time I think this would be an issue is if your delete button gets moved to the detail view _(the second row which expands and collapses)_ on smaller resolutions. When creating the detail view only html is copied across, event bindings and such would be lost on any buttons moved to the detail view.

Thanks
Steve

**Comment by ggeiger** [comment]
Hey! Thanks for the reply. You're correct, the delete button is being moved. Here's my table head:

```
<thead>
            <th data-class="expand">Thumb</th>
            <th>Event Title</th>
            <th data-hide="phone,tablet">Description</th>
            <th data-hide="phone">Date</th>
            <th data-hide="phone,tablet">Options</th>
          </thead>
```

The delete button in inside Options

**Comment by steveush** [comment]
Ok, this is more an issue with how to traverse the DOM and bind with jQuery than an issue with the plugin as it is doing what it's supposed to and creating the detail row, it's the custom removal causing issues.

That said I could probably look at adding some functions to assist with this, but in the mean time I'm always happy to help out where I can and I think there are only really two options available to you:
- **Option 1**
  Stop the column being moved to the detail view on smaller resolutions by removing the **data-hide** attribute from the **th**.
- **Option 2**
  If you want the button moved to the detail view and still function as expected you will need to change the way the button is bound and how it detects it's parent/detail row. The most widely supported method would be using **.delegate()** to bind the **click** event at the table level so as to only have a single event bound for all the delete buttons. You will also need to check whether or not you're in the detail row so you can get back to the original parent row and vice versa.

An example of **Option 2** using **.delegate()** (jQuery 1.4.3+ - superseded from 1.7 by .on()):

``` javascript

$('.footable').delegate('.delete-event', 'click', function(){
    var $button = $(this), //the clicked button
        id = $button.attr('id'), //get the id from the button
        post = { 'id': id }, //create the post data
        $current = $button.parents('tr:first'), //the current row the button is in
        $remove; //variable to add the rows needing to be removed to

    //if we in the detail row or not
    if ($current.hasClass('footable-row-detail')){
        //get the previous row and add it with the current row to be removed later
        $remove = $current.add($current.prev());
    } else {
        //get the next row after the current row and check if it's a detail row
        var $next = $current.next();
        //if the next row is a detail row or not
        if ($next.hasClass('footable-row-detail')){
            //get the next row and add it with the current row to be removed later
            $remove = $current.add($next);
        } else {
            //we can't find a detail row so just remove the current row later
            $remove = $current;
        }
    }

    //post the filename to the delete page
    $.ajax({
        type: "POST",
        url: "delete-event.php",
        data: post,
        cache: false,
        success: function(){
            $remove.css("background", "red");
            $remove.fadeOut(function() {
                $remove.remove();
            });
        }
    });
    return false;
});

```

Please note I wrote this in notepad++ so there may be some syntax mistakes and it looks rather bloated due to all the comments but I just wanted to make sure you know what's going on ;)

Thanks
Steve

**Comment by steveush** [comment]
Closing this as it's not a plugin issue and has been answered with no response.

**Comment by ggeiger** [comment]
This works brilliantly. Without changing a line, your code was spot on. Thank you for taking the time to help me with this.
