### ISSUE TITLE
Cannot reproduce the example with sorting API

### ISSUE THREAD

**Issue by geolens** [fooplugins/FooTable#270]
Hi,

I have a table with sorting enabled. It works fine with the header, but I need to sort using a button, so I added in my js the sorting API. 
When I click on the button, Google dev Tool  give me this error: http://imgur.com/qZPED6y

It's the var footableSort that is undefined. What do i do wrong?

Thanks!

**Comment by bradvin** [comment]
it is difficult to tell just from the screenshot. Can you recreate the issue on jsFiddle so that I can step through the code?

**Comment by geolens** [comment]
Sure! here's the fiddle : http://jsfiddle.net/geolens/4o39d3zq/

The last column is a timestamp and i'd like to sort the table on it with that column hidden, using the button above the table

Many thanks

**Comment by geolens** [comment]
bump!

**Comment by bradvin** [comment]
I had a look at your jsfiddle and could see the problem. But that was caused by your sort scripts not loading. I was getting errors from rawgit.com so the scripts were not loading into the page.

So I copied it locally, and recreated your demo pointing to local footable scripts and css. It worked 100%, including the button which sorted the table chronologically.

So at this point I cannot reproduce your problem
