### ISSUE TITLE
Wrong breakpoint calculation

### ISSUE THREAD

**Issue by SLemming** [fooplugins/FooTable#272]
It seems that footable is calculating the breakpoints wrong.

``` javascript
$('table').footable({
    breakpoints: {
        phone: 500,
        tablet: 800
    } 
});
```

And set some cols to data-hide="phone".

And in the CSS I define:

``` CSS
@media screen and (max-width: 500px) {
...
}
```

But it seems, that die JS hides the the columns at about 520/530px - which causes a wrong table layout because the mediaqueries are not valid yet.
What can be the problem? Is there a fix?

**Comment by SLemming** [comment]
I generated a codepen example. You can see the effect here as well, but it's not that obvious than in my project (less than 20px I guess).
http://codepen.io/anon/pen/AGzyp

**Comment by steveush** [comment]
Hi,

Been a while since I have looked into FooTable however looking at the code it seems as if there has been a change to the calculation of the widths. By default FooTable will use the width of the parent element by to adjust itself. Personally I think this is incorrect and it should solely work off the viewport but you can override it using the calculateWidthOverride option as you can see in this modified version of your pen: http://codepen.io/anon/pen/xdJpo

Thanks

**Comment by SLemming** [comment]
Thanks so much. Your override function works perfectly for me :)
