### ISSUE TITLE
Breaks modal hiding on bootstrap on mobile

### ISSUE THREAD

**Issue by Znuff** [fooplugins/FooTable#273]
See http://jsfiddle.net/1x5d8hg9/

On min-width: 768 there's no issue with the modal going away.

Once mobile view kicks in (resize the output), triggering the modal works fine, but when you dismiss it, the black overlay never goes away.

**Comment by steveush** [comment]
Hi,

This issue is caused due to the way FooTable works, the way your cell content is created, and the way the popover plugin receives it's content via ID. FooTable duplicates cell contents from the original row to the collapsible row and in this case it is duplicating your hidden modal div which has an ID that the popover plugin uses. It seems that bootstrap opens two overlays due to there being two of the same ID on the page once in mobile view and when you click close only a single overlay is removed, not both. You can see what I mean by looking at this [modified version](http://jsfiddle.net/1x5d8hg9/3/) of your fiddle which just moves the modal div outside of the table to prevent it being duplicated and then the popup works again as expected. Unfortunately this is core to the way FooTable works currently so there are two possible options I can see straight off the bat for you going forward:
1. Change the render of the cell and move the modal's out of the table as in the modified fiddle.
2. Change the way your buttons interact with your popup, make the button click pass it's data to a single instance of the modal which allows you to edit etc. and on close modify the entry.

Personally I would implement the second option simply due to the amount of HTML you would not have to render to the page every time. For example in your current configuration if your list contains 100 IP addresses you would have to output basically the exact same HTML 100 times for each modal, which is massive bloat for your page. Going with option 2 would mean you only have to output the HTML for the modal once and all IP address buttons make use of it.

Thanks

**Comment by Znuff** [comment]
I should have closed this earlier, as I managed to figure it out by myself.

Right now I simply moved the HTML out of the table and it works just fine.

Thanks for suggesting the 2nd option. I didn't really think of that. Will do.
