### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kevin-brown** [fooplugins/FooTable#29]
I'm considering switching from DataTables to FooTable, but the lack of pagination is holding me back at the moment.

DataTables has great support for pagination, which is needed when you are dealing with large data sets.  FooTable doesn't appear to support this through any of its plugins, which means that you would have to scroll past all of the loaded data to get past the table.

I understand that FooTable is supposed to be fairly lightweight, but how often are you dealing with tables that need to be responsive but don't contain a large amount of data?

This would also help with limiting the amount of data that needs to be queried when loading FooTable if you were using AJAX which was mentioned in #16.

**Comment by steveush** [comment]
Hey Kevin,

I'm currently working on a fairly substantial change to the underlying framework the plugin is built on to be able to provide better extensions and addons while reducing the amount of code required to write those. Once this is complete I'm definitely going to take a look at making a pagination plugin and providing more events and support for ajax requests. I'm just taking some time to get the base right as if that's shaky everything built on it will be as well :) The current FooTable version was actually done more as a POC than as a release plugin and is driving the way I build the new framework taking into consideration the issues listed here.

So thanks for the feedback, it's always welcome and I'm pretty sure pagination and better ajax support will be available in the not so distant future ;)

Steve

**Comment by alonextou** [comment]
I would also love to see this feature, in fact I am currently building it on my own, but not as a plugin. I could consider writing it as a plugin, but if I went that route I'd like to know if you are planning a rewrite which could break backward compatibility. FooTables is a great POC but I'm sure you've noticed it has tremendous potential (to be better than DataTables), so let me know if you would like help on this :)

**Comment by bradvin** [comment]
We do realise that Footable needs a pagination add-on. We also believe that Footable can be better than Datatables  - that is why we wrote it in the first place - because we were sick at how difficult datatables was to use and customize. Steve and I would love to get some help on this. It will also be a very good test for the addon framework Steve built into Footable, to make sure it is flexible enough going forward. If you can help with this add-on, then please do :)

The major refactor change Steve is doing at the moment "should" not break anything you write at the moment, and if it does, it should be pretty simple to fix.

**Comment by Bramjetten** [comment]
+1 I've already started using FooTable and the only thing missing for me is pagination and AJAX. Right now I'm doing what awc737 is doing.

**Comment by JefferE** [comment]
+10 on pagination and ajax. Rarely get a request to build a site with data tables where the dataset is usable within a scrolling div.

**Comment by railapex** [comment]
Any news on this? I really love the FooTable concept -- it's exactly how I want to do responsive tables down to the phone.

However, I need to fill data through AJAX and use server side sorting/filtering, so it isn't currently workable for me at this point.

How is the refactor coming along? I'd love to contribute a plugin for this, but I'd hate to duplicate effort or get my plugin broken by the refactor and have to rewrite.

I also don't see a good way to snap in the data loading as a plugin, particularly if I want to play nice with other plugins like sortable/filterable since that needs to be done server side.

**Comment by steveush** [comment]
Hey Guys,

I've pretty much finished the re-factoring and included a number of fixes and enhancements while doing it. Pagination and Ajax support is underway.

Some of the enhancements I've finished are:
1. No longer require headers. FooTable can be setup using colgroups or directly through the options.
2. Advanced option handling and method calling using the FooTable constructor. It's now possible to call methods by using code like **$('.footable').footable('someMethod', param1, param2, etc)**. This for example allows for programmatic calling of sorting or filtering instead of having to trigger events. 
3. Better default CSS support for the detail row as well as some changes to the main CSS.
4. The expand/collapse icon is now included by default, no need to use the **data-class** attribute to add the **expand** class. The toggle button can be disabled using the new **showToggle** option. I did it this way as the first column can change depending on the breakpoints set.
5. FooTable and it's addons now actually have a reinit method so calling the constructor twice won't trigger a full reload of the plugin, only what's required to reapply it. This is useful if you load rows via ajax, directly after you have appended the rows you can call **$('.footable').footable()** to reinit the plugin to recognize the new rows. If a sort or filter exists it will be reapplied.

I must actually check-in a new branch with all the changes so people can start trying it out. I think it's a lot more solid now than it used to be and the CSS cleanups have made quite a difference, no more double borders or cut off rounded corners on row hover etc.

Thanks
Steve

**Comment by alonextou** [comment]
@steveush where are these changes? I don't seem them reflected in the master branch currently.

**Comment by alonextou** [comment]
UPDATE: woohoo! Everything is working great: https://github.com/bradvin/FooTable

I would probably consider this issue resolved.

**Comment by svenspielvogel** [comment]
The re-init isn't working yet, is it?

**Comment by bradvin** [comment]
Rather trigger the custom event footable_resize like so:

$('table').trigger('footable_resize');

This will call the footable resize function which will redraw the table and do everything you expect from the re-init while keeping all the bindings in place
