### ISSUE TITLE
Enhance paging results for V3

### ISSUE THREAD

**Issue by claudchan** [fooplugins/FooTable#341]
Hi,
Is it possible to have paging results to show like "Showing 1 to 10 of 1000 entries" instead of "1 of 1000"?
Hope that this will implement in V3.

**Comment by steveush** [comment]
Hi,

I just want to point out it is showing "1 of 1000" as page 1 of 1000 pages. 1000 is not the total number of rows but rather the total number of pages, hence why it only shows "1 of 1000" instead of something like "1 to 10 of 9856" where 9856 would be the total number of rows.

That said I have added in an option to let you specify your own simple format using a limited number of supported placeholders/tokens. Take a look at the new [countFormat](http://fooplugins.github.io/FooTable/docs/components/paging.html#countFormat) option which would allow you to create the results requested above by using the **{PF}**, **{PL}** and **{TR}** placeholders as follows **"Showing {PF} to {PL} of {TR} entries"**.

Thanks
