### ISSUE TITLE
Detail headers don't seem to work

### ISSUE THREAD

**Issue by tonycurwen** [fooplugins/FooTable#36]
This is a strange one, as I'm sure they do work because all the demo's work.

However when columns collapse on my table the detail row fails to show the table headers in bold as they do in the demo's.

If I change the createOrUpdateDetailRow function as follows:

```
    // if (index in column.names) name = column.names[index];
    if (index == column.index) name = column.name;
```

Then it all works for me. I can't anything obviously wrong with table/thead/tr/th or table/tbody/tr/td config.

**Comment by steveush** [comment]
Hi Tony,

I'll look into this a bit more as the line you've changed was added to allow for columns with a colspan'd header to still have separate names. You should in fact be able to simply comment out that line without adding anything and the **column.name** value will be used as it is set when the **name** variable is declared.

To explain what that line of code should have been doing is check if the current **index** exists within the **column.names** object which is built up from the **data-names** attribute and use that value instead of the current **column.name** value. The **data-names** attribute accepts a comma separated string of names to be used for the columns the header is spanning.

Obviously I've overlooked a particular situation where **index in column.names** is returning a false positive and is overriding the **column.name** value.

Thanks
Steve
