### ISSUE TITLE
V2: "Sort is undefined" error

### ISSUE THREAD

**Issue by calvinang** [fooplugins/FooTable#363]
Hi there,

Sorry for the duplicate post; I'm a bit confused as to what the preferred method for FooTable support questions is. We just noticed that there were questions here as well so figured that it's worth a shot. 

I have an issue where sorting sometimes yields a “sort is undefined” console error. In one case I found that the error seemed to be because I was calling $().footable() twice, once for initialization and another for the bind(). Removing the second footable() call removed the error in most cases.

However, I have other pages where the error occurs. In one case, it occurs after every other sort. When the error does occur in this case, the sort does NOT occur, but clicking the column again activates the sort without any issues. A subsequent click of the same column generates the same error, while a further subsequent click produces a successful sort, and so on. Update: In this particular case, there are two tables on the page, but only one where sorting actually occurs. 

In another case, the error occurs every time the column is clicked, but the sort still occurs in spite of the error. Update: In these cases, there is only one table on the page, and I've already addressed the issue of calling FooTable twice.

The error seems to happen when ft.columns is inexplicably null, but other parts of the ft internals are (at least from what I can see) clearly defined.

It’s also worthy of noting that I am actually pulling sorted data from the server every time a column is clicked. Basically we are using footable for its detail/table rendering capabilities and not primarily for sorting and filtering. I call .doSort just to accomplish the arrow changes. In theory, it should not matter because the table is completely overwritten after each server call; the table is essentially populated in a div marked with an angularjs ng-view. However, because footable itself is being included in a higher parent scope, I’m assuming that there may be some saved state involved.

I have three questions:
1. Any ideas as to why this error is occurring in general?
2. Is there some sort of method I can call to reset any saved state that may be contributing to the error once new data is obtained from the server?
3. Is there some other way to accomplish the arrow (descending/ascending) changes, since really I’m just forcing a sort just to produce these screen changes?

I have been trying to create a jsFiddle but am unable to replicate the behavior. In fact, the one I created refuses to sort after the first sort. No error is occurring. I will keep trying, however.

I am happy to pay for any follow-up support, but there does not seem to be an option to do so.

Thanks,
-calvin

**Comment by steveush** [comment]
Hi,

In your instance I think you can do away with the sorting plugin all together. I'm not sure if there is state being saved as I have not tried V2 with Angular myself however nothing should be stored.

Anyway on to getting rid of the sorting plugin for your specific case, firstly don't include the footable.sort.js in your page ;)

You will then need to make some changes to the HTML for your table headers. First you will need to add the `footable-sortable` CSS class to each `TH` or `TD` that you want to be sortable. Second you will need to add a `SPAN` to each of the sortable cells with a CSS class of `footable-sort-indicator`. So basically instead of your cell looking like this:

``` html
<th>
    My Header
</th>
```

They would instead look something like:

``` html
<th class="footable-sortable">
    My Header
    <span class="footable-sort-indicator"></span>
</th>
```

Once you have the above working the below shows how I binded the click events to toggle the indicator. From what you have said you already have a custom click event to retrieve the data from the server so you should be able to just pop my code in there.

``` javascript
$('table').footable().on('click', '.footable-sortable', function(){
    var $this = $(this),
            index = $this.index(),
            sorted = $this.hasClass('footable-sorted') || $this.hasClass('footable-sorted-desc'),
            asc = sorted ? $this.hasClass('footable-sorted') : false;
    $this.closest('table')
            .find('thead > tr:last > th, thead > tr:last > td').removeClass('footable-sorted footable-sorted-desc')
            .eq(index).addClass(asc ? 'footable-sorted-desc' : 'footable-sorted');
});
```

The above is fairly self explanatory and is basically just swopping out the `footable-sorted` and `footable-sorted-desc` CSS classes on the cells. If you start with a sorted column use one of these two classes to specify the sort direction on the cells like so:

``` html
<th class="footable-sortable footable-sorted-desc">
    My Header
    <span class="footable-sort-indicator"></span>
</th>
```

Thanks and I hope that helps.

**Comment by calvinang** [comment]
@steveush Thank you so much! I will be trying the above out soon. I actually had something like it previously, but I was including the sort js file thinking that it would be required for general operations. Of course, the resultant behavior was the table returning to its original state every time. Oops. :)

**Comment by jeffconklin** [comment]
@calvinang How did this go for you?

**Comment by calvinang** [comment]
@jeffconklin Thanks for checking in. I had to adapt it a bit to fit what we were doing server-side, but in general, your approach worked handsomely. Thanks again!
