### ISSUE TITLE
V3: future paid support

### ISSUE THREAD

**Issue by calvinang** [fooplugins/FooTable#364]
Hi there,

I was looking into upgrading to V3 of the FooTable jQuery plugin and was wondering if you folks were planning to bring back paid support at some point. I don't mean to pester you folks too much; it's an awesome product that does quite a bit in terms of features. But given that I still have a couple of open issues with you folks (including https://github.com/fooplugins/FooTable/issues/363), I'd feel much more comfortable if I had some idea of your future plans before embarking on what could be a time-consuming upgrade. 

Thanks in advance for understanding! Looking forward to your reply.

-calvin

**Comment by steveush** [comment]
Hi,

I'm sure this is no longer relevant to you as this issue was opened long ago and lost in the sea of V2 issues however I am presently cleaning up the repo and closing all issues I can. In response to your question we do still offer paid support for V3 however we would encourage you to use the issues here on the repo as firstly it's free and secondly other users may be able to answer the question for you.

Thanks
