### ISSUE TITLE
V3: FooTable not calculating width correctly

### ISSUE THREAD

**Issue by craigmatthew412** [fooplugins/FooTable#366]
Internal FooTable function getViewportWidth() is incorrectly calculating width on HiDi screens.  For example, when my iPhone 6 is in landscape view, it is returning a width of 333.5 instead of 667 because it is dividing by window.devicePixelRatio (2 in this case). This is then incorrectly setting the breakpoint classes.

Using the getWidth column function override is a usable workaround, but wanted to make sure someone either a) saw this issue or b) verified this was the intended purpose

**Comment by steveush** [comment]
Hi,

Thanks for posting this, it was unfortunately lost in the sea of old V2 issues and I've come across it now during a repo clean out. I've since tested this and agree the old method of checking the devicePixelRatio is not needed and I have since changed it, it will be updated in the next release.

Thanks
