### ISSUE TITLE
HTML type column with iCheck checkbox bug

### ISSUE THREAD

**Issue by GarryP** [fooplugins/FooTable#389]
Updating FooTable from version 2.0.1.5 to 3.0.4. Within the header we have one iCheck checkbox to check \ uncheck all the other iCheck checkboxes within the grid. The individual checkboxes within each row (non header) work fine you can check and uncheck them, clicking the checkbox within the header will not work no event fired and the checkbox stays checked.

**The HTML:**

&lt;th data-sort-ignore="true" data-sortable="false" data-type="html"&gt;
           &lt;div class="ChkAll"&gt;
                &lt;input id="veh_all" name="ShowVehicle" type="checkbox" checked rel="icheck" class="check_all checkable-primary" /&gt;
         &lt;/div&gt;
&lt;/th&gt;

**The JavaScript:**

```
$('.ChkAll').on('ifToggled', function () {
    if ($(this).checked) {
       $('.liveLocChk').find(':checkbox').each(function () { $(this).iCheck('check'); });
       $('#AllItemsSelected').val('true');
    }
    else {
       $('.liveLocChk').find(':checkbox').each(function () { $(this).iCheck('uncheck'); });
       $('#AllItemsSelected').val('false');
    }
});
```

**Comment by steveush** [comment]
Hi,

Apologies this is long overdue, the issue was that the sorting component worked off of a click on the entire `TH` element and had a call to `e.preventDefault()` in the handler. This was basically killing the default click behavior of elements placed within the header element. I've since removed this limitation and it will be released in the next version shortly.

Thanks

**Comment by jmserrato** [comment]
was this issue solved? I have the same problem, i'm using the version 3.1.5
