### ISSUE TITLE
Sortable Bug

### ISSUE THREAD

**Issue by khookguy** [fooplugins/FooTable#4]
Sort not working correctly on Date column (using data-value =  Unix epoch time).

See the bug here:   http://marktest.digitalbrandmine.com/bug

To see the bug, sort on date and notice that the top row with date 2012-11-28 is out of place.  Sort on a few other columns, and then come back and sort on Date again, and you will see the sort order even more messed up.

**Comment by bradvin** [comment]
had a look at your table and you have not specified data-type="numeric" on the date column table header. When sorting dates, you need to tell footable that the data is numeric in order to sort by the unix timestamp data-value

You did include the data-type="numeric" on the reach column, but the others need it too.

**Comment by khookguy** [comment]
Thanks!  Now, it is working.  Great work with Footable!
