### ISSUE TITLE
Comma as Decimal Separator

### ISSUE THREAD

**Issue by mqueirozcorreia** [fooplugins/FooTable#404]
How can I set the numeric separator? In v2 I could use "," comma with no problem, but in v3 it ignores the comma as a decimal separator and create a big number. It only works when using "."

**Comment by steveush** [comment]
Hi,

The issue here is JavaScripts [parseFloat](http://es5.github.io/#x15.1.2.3) function which is used for number columns parses string values according to the JavaScript [definition of a decimal literal](http://es5.github.io/#x9.3.1), not your locale's definition. (i.e., parseFloat is not locale-aware.) Decimal literals in JavaScript use a period for the decimal point.

I'll see if I can find a way around this for the number column.

Thanks

**Comment by steveush** [comment]
Hi,

I have added additional options for number columns in the latest version (3.0.6), please take a look at the [updated docs](http://fooplugins.github.io/FooTable/docs/columns/number.html) for details however you should just need to set the new periodSeparator option to a comma (,).

Thanks
