### ISSUE TITLE
If no rows exist in table the plugin inproperly errors out on .preInit()

### ISSUE THREAD

**Issue by blindMoe** [fooplugins/FooTable#409]
If you are using a server side language such as php or c# and you are creating a display table that does not yet have rows ( IE: The index of a CRUD scaffolding whose model has no entries ) the plugin throws an error un-gracefully.

FooTable: unhandled error thrown while executing "preinit". Error: No rows supplied.(…)

To mimic this just run:

&lt;table class="footable">
  &lt;thead>
    &lt;tr>
      &lt;th>Header 1&lt;/th>
    &lt;/tr>
  &lt;/thead>
  &lt;tbody>
  &lt;/tbody>
&lt;/table>

**Comment by allenfantasy** [comment]
Same error here. Very frustrating.

Different from @blindMoe, I am using the JS-way:

``` js
$('.table').footable({
  "toggleColumn": "last",
  "expandFirst": true,
  "empty": "no results",
  "columns": [
    { "name": "id", "title": "ID", "breakpoints": "xs" },
    { "name": "firstName", "title": "First Name" },
    { "name": "lastName", "title": "Last Name" },
    { "name": "jobTitle", "title": "Job Title", "breakpoints": "xs" },
    { "name": "started", "title": "Started On", "breakpoints": "xs sm" },
    { "name": "dob", "title": "DOB", "breakpoints": "xs sm md" }
  ],
  "rows": []
});
```

(Actually I am coping the example from documentation but just change the `rows` to empty array)

**UPDATE** just check [the source](https://github.com/fooplugins/FooTable/blob/1d5f26c418ace6c9e204769879f82fea5d1adb2b/src/js/components/internal/rows/FooTable.Rows.js#L81) [code](https://github.com/fooplugins/FooTable/blob/1d5f26c418ace6c9e204769879f82fea5d1adb2b/src/js/components/internal/rows/FooTable.Rows.js#L115). It looks like this behavior is designed to be acted like that.

But this behavior would cause a BIG misunderstanding since in FooTable's [document](http://fooplugins.github.io/FooTable/docs/getting-started.html) it says the "rows" default value is an empty array. So here's a contradiction.

I don't know if this should be considered a BUG or not. If it's not a BUG, the documentation should be updated to prevent people dropping empty rows in it and pulling hears off.

**Comment by steveush** [comment]
Hi,

You can get around this by changing the FooTable.Rows.parseFinalize method, simply include the below after you have included FooTable but before you initialize the plugin.

``` javascript
FooTable.Rows.extend('parseFinalize', function(deferred, rows){
    var self = this, result = jQuery.map(rows, function(r){
        return new FooTable.Row(self.ft, self.ft.columns.array, r);
    });
    deferred.resolve(result);
});
```

I might just remove the error being thrown all together however I would need to do some testing to make sure it doesn't cause any issues further down the line. Depending on what I do I'll update the docs accordingly.

Thanks

**Comment by allenfantasy** [comment]
Thank you for the reply!

For now we check if the table data is empty before initialize FooTable. May try this workaround later to see if it works.

Again thanks for your help. If there's something I could help ( like testing the patched code ) I would be glad to help. ;)

**Comment by steveush** [comment]
Hi,

I decided to remove the error from the code so the table can now initialize with no row data at all. I've updated the docs accordingly.

Thanks

**Comment by brestfloda** [comment]
Hi,

I simply cannot get this to work... I have a working site using FooTable-2 as a local CSS-resource and i want to change it to a CDN-delivered FooTable-3. I've tried putting in the above script in the order:
1.     link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/3.0.7/footable.core.css" rel="stylesheet" type="text/css"
2.     script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"
3.     script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/3.0.7/footable.js" type="text/javascript"
4. ASP.NET gridview with footable class
5. Script as indicated above
6. $('.footable').footable();

Any help?
