### ISSUE TITLE
[V3 Question] Non expandable rows

### ISSUE THREAD

**Issue by rhalaly** [fooplugins/FooTable#417]
I want to make some non expandable rows.
For example: https://jsfiddle.net/r6jqv56o/1/

(By the way, you can see in the example that you have bug when using "colspan". It adds the "missing" columns and makes the row bigger then table)

How can I get such behavior?

**Comment by steveush** [comment]
Hi,

At the moment this is not supported. The reason is simply how should these rows be handled when sorting, paging or filtering? I'll look into it for future integration but I couldn't give a timeline as it would need to work with all supported components to be included in the plugin.

V3 was created to be easily extended (_take a look at the [custom filter dropdown example](http://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html) to see how FooTable objects can be extended_) and everything is documented in the [JSDocs](http://fooplugins.github.io/FooTable/docs/jsdocs/index.html), so if you don't need the default components, as in your fiddle, you can create a custom one or modify the base ones to fulfill your needs.

Thanks

**Comment by rhalaly** [comment]
If you asking me, this rows should be ignored and be static. So sorting, paging and filtering will skip them and leave them in the same place, like banners.
