### ISSUE TITLE
Some problems in Footable?

### ISSUE THREAD

**Issue by JujuPomme** [fooplugins/FooTable#463]
Hey All,

I've really some strange things with Footable.
I have to display a table when I click on a tab but, each click, there is some things very strange like a column is added, a class is added to my table, the displayed of my table works one in two...

Someone have an idea about theses things? I don't want to modify the source code...

Thanks !

**Comment by steveush** [comment]
You already have an issue open for this, why are you opening more? Also most of these issues seem related to your implementation of the plugin. I am doing what I can to resolve any problems I can replicate but as I have asked in your other issues please provide me a testable jsfiddle or else I will be simply closing these.

Thanks

**Comment by JujuPomme** [comment]
I don't know how can I add a column whereas there are in a file by default. I don't see why a class is added on my table when I click on a tab... So don't tell me that it's my implementation whereas I fix the class' problem to erase a line in your source code....
I'll give you a testcase during the day.

Thanks for your answer

**Comment by JujuPomme** [comment]
Maybe can I send you some files?

**Comment by steveush** [comment]
Hi,

The additional class being added to the table is something I have found and fixed, but it has no actual effect on the table layout. The additional classes being added are simply `footable-1`, `footable-2`, etc. which have no CSS properties associated to them, they are just used to identify the table as the first, second, etc. instance of FooTable. Every time you call the constructor on the table (each tab click) the plugin is destroyed and recreated. So it adds another class increasing the count. For example the first time you load the page the table will have `footable-1`. When you click your tab it will then have `footable-2` added to it's classes and so on and so forth. The fix I made for this is that when the table is destroyed the previous class is now removed as well. So instead of ending up with each class on the table like `footable-1 footable-2 footable3` etc. you now only get `footable-2` or `footable-3`. But again these classes are there purely to represent the instance count and have no actual effect on the table as they have no CSS properties defined, in fact they don't even exist in the style sheets.

If you can create a jsfiddle, please do, it doesn't need to use your data, it just needs to be simple enough to reproduce the problems so I can see them in action. I would love a chance to debug the issues and resolve them, it's just highly frustrating having multiple issues created for the same/similar problems without any way to resolve them without guessing wildly as to there cause, especially working in a language such as JavaScript which is so extremely flexible.

This is also a free plugin which I only work on when I have the time available, the source code is here on GitHub so it can me modified to suite your needs as every project can have different requirements. FooTable v3 was made to be extendable so that it can provide you with a decent base to start working from and as you need it you can implement what you need. As an example the below piece of code would fix the CSS class issue mentioned above without having to modify any of the source code, you would just add it into the page after you have included FooTable (this is basically the fix I have implemented on my local repo):

``` javascript
FooTable.Table.extend('destroy', function(){
  var self = this;
  return this._super().then(function(){
    self.$el.removeClass('footable-' + self.id);
  });
});
```

To figure out more on how to extend FooTable without modifying it's source code please take a look at the examples for the custom filtering UI and filter dropdowns in the documentation. Also take a look at the jsdocs or the source code to see how it all fits together.

Thanks

**Comment by JujuPomme** [comment]
Thanks for your informations but that problem, I solved it alone.

How can I include the Footable plugin in JsFiddle?

**Comment by JujuPomme** [comment]
I have something like that but it's not working : https://jsfiddle.net/xh353koa/

**Comment by steveush** [comment]
Ok, no problem, on the left hand side of jsfiddle it says something along the lines of **External Resources** which gives you the ability to insert external JavaScript and CSS files to use in the fiddle. The order in which you insert them is the order they are loaded into the fiddle. So you will need to add jQuery and then FooTable. FooTable is hosted on CDNJS so you can use the below urls to include it:

`https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/3.0.10/footable.js` for the JavaScript.
`https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/3.0.10/footable.standalone.css` if you use the standalone version.
`https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/3.0.10/footable.bootstrap.css` if you use the Bootstrap version.

Thanks

**Comment by JujuPomme** [comment]
I can't reproduce my problem and I don't know why. I've this fiddle now : https://jsfiddle.net/xh353koa/1/
And it's working (I think) when I click on the reload button.

Maybe I can send you some files to allow you to see the problem?

**Comment by JujuPomme** [comment]
The only problem present on the fiddle is when you have a child row, and click on reload, it create a new row. But it's maybe because I forgot some files...

**Comment by steveush** [comment]
Make sure to save/update the fiddle, the link above points to the original one with no JavaScript files included. You can see the end of the url is `/1/` when it's saved it will display as `/2/` and so on. Also the links to FooTable I provided above point to version 3.0.10 which is a what I pushed out this morning and contains fixes for most of the issues you already logged so if you change your local version to use 3.0.10 do you still only have the row issue? If so please update the fiddle and send me the new link and I'll see if I can spot why you are seeing duplicate rows.

**Comment by JujuPomme** [comment]
I have duplicate rows only on the fiddle. And for the displaying of the table, it's working on the fiddle... 

I haven't update the fiddle, sorry, here's the new link : https://jsfiddle.net/xh353koa/3/

**Comment by JujuPomme** [comment]
Ok so I fix everything... It's not really fixing, it's just hiding the things I don't want, and it works well for the moment.

Just one more thing. Do you have an idea, why a column is added each time I click on my tab? Where can I delete this part of code?

Thanks a lot for your answers today, you was really great and I hope that my english wasn't too bad. :/
