### ISSUE TITLE
Inconsistency of how breakpoint works between v2 and v3

### ISSUE THREAD

**Issue by Ariex** [fooplugins/FooTable#468]
In the older version (2.0.3), the current breakpoint is first the bp that wider than screen width. But in V3 (3.0.10) it is the breakpoint that the first one smaller than screen width.
For example, same break point settings:

```
breakpoints{
"lg": 1200, // large
"md": 992, // medium
"sm": 768, // small
"xs": 480 // extra small
}
```

if i have

```
<th data-breakpoints="xs">
```

for the old version, this column will collapse when table width is 480; and for V3, this column will collapse when screen less than 768.

I have created two demos:
http://codepen.io/Ariex/pen/WxeBpO
http://codepen.io/Ariex/pen/QEwJOr

you can drag the vertical spliter to see how those two things work differently

**Comment by steveush** [comment]
Hi,

You are correct that the behavior has changed slightly and the reason for it was to bring it inline with Bootstrap's breakpoints and how they function. If you look at http://getbootstrap.com/css/#responsive-utilities and compare the table there to the one found in FooTable's documentation for breakpoints http://fooplugins.github.io/FooTable/docs/getting-started.html#breakpoints you will see they match up. This was done so that whenever a breakpoint changes in Bootstrap and possibly alters the layout of your site FooTable matches it step for step.

Thanks
