### ISSUE TITLE
This project is included in npm? If so on what name?

### ISSUE THREAD

**Issue by vs0uz4** [fooplugins/FooTable#473]
I tried to install the plugin through the npm however not find it in any way. It lies included in npm?

https://www.npmjs.com/search?q=footable

**Comment by steveush** [comment]
Hi,

At present it is not included in NPM due to this one repo basically having three outputs, the Bootstrap version, the Stand Alone version and the component version. If you prefer to not download the plugin you can use the CDNJS urls provided at https://cdnjs.com/libraries/jquery-footable.

Thanks
