### ISSUE TITLE
Why my moment.js date seems not functioning ? 

### ISSUE THREAD

**Issue by skyrichkoh** [fooplugins/FooTable#479]
Anyone when select "Edit", the 2 dates appear as dd/MM/yyyy instead of the actual date in the table

![image](https://cloud.githubusercontent.com/assets/20349024/16676527/8927674a-44fd-11e6-9871-20cec9813893.png)

Also when I click on Add New Row and Save, the new row's date appeared as a long numbers

![image](https://cloud.githubusercontent.com/assets/20349024/16676541/b50aca96-44fd-11e6-8ee2-3882699823d0.png)

![image](https://cloud.githubusercontent.com/assets/20349024/16676544/bf164092-44fd-11e6-9f8e-1a2ad68d0de6.png)

**Comment by steveush** [comment]
Hi,

I couldn't say why just by looking at the screenshots but I am guessing it is due to date format issues with the input type date element.

The first issue where dates are not appearing I think comes down to input type dates expect there value to be supplied in the `YYYY-MM-DD` format, if you look at the [example](http://fooplugins.github.io/FooTable/docs/examples/component/editing.html) you can see whenever I set the input value I supply my dates in that format.

I think it's a similar reason why your newly added dates appear as integers. Looking at the previous example when I save a row I create a new moment object using the input value and the `YYYY-MM-DD`. The reason is when you call `$('input[type="date"]').val()` it returns the value it the default format of `YYYY-MM-DD`.

Thanks
