### ISSUE TITLE
FooTable 3 on IE8 - unhandled error thrown during initialization

### ISSUE THREAD

**Issue by claudchan** [fooplugins/FooTable#488]
Does FooTable 3 be support at least IE8?
Came across with IE8 error:
<code>
FooTable: unhandled error thrown during initialization. TypeError: Unable to get property 'constructor' of undefined or null reference
</code>
Any fix around?

**Comment by whyisjacob** [comment]
I am seeing the same error but on Chrome

**Comment by steveush** [comment]
Hi,

@claudchan FooTableV3 is not IE8 compatible at present and was initially created with just IE9 upwards in mind. I'm not 100% sure at present what would be required to get it to work on IE8 but for a start there are utility functions that would need to be renamed like `FooTable.arr.delete`. IE8 will die trying to parse this due to the name also being a reserved keyword.

@whyisjacob You should not being seeing this in Chrome, the only way I can think of is if there is something incorrect in your config and the plugin is throwing out the error due to it. Please open a new issue with more details on your error, a jsfiddle demoing the issue will be best.

Thanks
