### ISSUE TITLE
Restore default filtering

### ISSUE THREAD

**Issue by stavrianosy** [fooplugins/FooTable#505]
I have a footable in 2 different pages in my SPA application.
In pageA I implemented an extended filtering based on the following example and I have a dropdown filtering along with a search box:

[Filter dropdown](https://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html)

When I visit the pageB though I still can see the extended dropdown filtering which is not applicable there. 
How can I reset the filtering to its default value and remove the ddl to display only the searchbox?

**Comment by steveush** [comment]
Hi,

You just need to not include the code that modifies the filter component on pageB. The example you linked to basically modifies the base files for FooTable, so all tables on the same page would have this change applied. I would create the filtering changes in a separate file and only include it on the page that needs it. If you need to have custom filtering and you have more than two tables in a page and only need to apply it to one of them then I suggest looking at the http://fooplugins.github.io/FooTable/docs/examples/advanced/custom-filter-ui.html example which should get you headed in the right direction. In the example the default filtering with the search box is hidden but that is done with just one line of CSS, you can if u like append to the original filtering UI instead of hiding it.

Thanks

**Comment by stavrianosy** [comment]
I do have the extended filtering in a helper js file but since I am using an SPA framework all pages are treated as one.
The example you suggested look ok but using that I will loose the searchfunctionality which is very handy.

**Comment by steveush** [comment]
Hi,

Even in SPA frameworks like Ember and the like the ability to load a single JS file for a single page still exists, it would be terrible if you had to load all your application JS at once. I'm not sure which SPA you're using but for example [Ember does it like this](http://stackoverflow.com/questions/28412001/ember-js-include-external-script-on-specific-page). As far as I know all frameworks should have this functionality built in, you'll just need to figure it out. As for losing the search functionality when using the [custom filter UI](http://fooplugins.github.io/FooTable/docs/examples/advanced/custom-filter-ui.html), you shouldn't. As I said in my previous comment the original search input is only hidden with a single line of CSS:

``` css
.footable-filtering {
    display:none;
}
```

If you don't include that then the original search input etc. are all shown.

Thanks

**Comment by stavrianosy** [comment]
The SPA i use is relatively new, it is the Aurelia framework.
The way SPA work (if i am not mistaken) is that they load the js or other resources, when any template/component (page) need them. Once a js file loads, it will remain cached for the rest of the navigation, therefore any changes I do globally to the FooTable will be applied to all instances, unless I overwite.

As for the other example, will give it a shot.

**Comment by steveush** [comment]
Hi,

In version 3.1.0 I have added in a [components option](http://fooplugins.github.io/FooTable/docs/getting-started.html#components) which allows you to load a custom component on a per table basis. I've updated the [custom dropdown filter example](http://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html), specifically step 6, which shows when to make use of this option.

Thanks

**Comment by stavrianosy** [comment]
Thanks, it worked.

How can i do "ignoreCase": false only for the new filtering component and not the search box ?

The below doesn't do!

$('.myTable').footable({
 "rows": result,
                "paging": {"limit": 10,"enabled":true, "size":15, "current":1,"position": "right" },
                "filtering": {"enabled":true,"ignoreCase": true},
                "components": {"filtering": filter, "ignoreCase": false}
            });

**Comment by steveush** [comment]
Hi,

The components option simply allows a custom component to be loaded into that instance of FooTable. That custom component still uses the other options just as the original would. In this case your options set `ignoreCase` to true for all filters but there is a work around that you can do. As you said you followed the [filter dropdown](https://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html) example so I'll use that to explain how you can do this. Basically in Step 4 of the example you need to remove the call to `FooTable.Filtering#addFilter()` and instead create a new instance of `FooTable.Filter` and simply add it to the current filters.

``` javascript
_onStatusDropdownChanged: function(e){
    var self = e.data.self, // get the MyFiltering object
        selected = $(this).val(); // get the current dropdown value
    if (selected !== self.def){ // if it's not the default value add a new filter
        var statusColumn = self.ft.columns.get('status'), // get the actual status column
            statusFilter = new FooTable.Filter('status', selected, [statusColumn], 'AND', true, false); // create the new filter
        self.filters.push(statusFilter); // add it to the current filters
    } else { // otherwise remove the filter
        self.removeFilter('status');
    }
    // initiate the actual filter operation
    self.filter();
}
```

The first three arguments for the [`FooTable.Filter`](https://github.com/fooplugins/FooTable/blob/V3/src/js/components/filtering/FooTable.Filter.js#L4) constructor are pretty much the same as the `addFilter()` method so they should be familiar, the biggest difference `FooTable.Filter` constructor expects an array of actual `FooTable.Column` objects instead of just the names. The last three arguments correspond to the [`space`](https://fooplugins.github.io/FooTable/docs/components/filtering.html#space), [`connectors`](https://fooplugins.github.io/FooTable/docs/components/filtering.html#connectors) and then finally the [`ignoreCase`](https://fooplugins.github.io/FooTable/docs/components/filtering.html#ignoreCase) options. The above example should set `ignoreCase` to false for your custom filter.

Thanks

**Comment by jeffconklin** [comment]
@steveush ... this is great. I will need to work with this in the next few weeks. I actually had to build a lot of my own hack filtering to allow for multiple situations like this on a page and it was ugly. This should help a whole lot. Thanks. And well done.

**Comment by steveush** [comment]
@jeffconklin thanks, there have been a few people that have asked about how to load a custom filter for just a single table and it was bugging me until now so this should resolve that.

@stavrianosy I made a small mistake in the above code example, you may end up with multiple status filters being applied. The below updated code should resolve that issue by first removing the filter and then only adding it if required.

``` javascript
_onStatusDropdownChanged: function(e){
    var self = e.data.self, // get the MyFiltering object
        selected = $(this).val(); // get the current dropdown value
    // first remove the filter to avoid duplicate filters
    self.removeFilter('status');
    if (selected !== self.def){ // if it's not the default value add a new filter
        var statusColumn = self.ft.columns.get('status'), // get the actual status column
            statusFilter = new FooTable.Filter('status', selected, [statusColumn], 'AND', true, false); // create the new filter
        self.filters.push(statusFilter); // add it to the current filters
    }
    // initiate the actual filter operation
    self.filter();
}
```

Thanks

**Comment by steveush** [comment]
Was thinking about this some more and decided to update the [`FooTable.Filtering#addFilter()`](https://github.com/fooplugins/FooTable/blob/develop/src/js/components/filtering/FooTable.Filtering.js#L305) method to expose the last three parameters of the `FooTable.Filter` constructor; `ignoreCase`, `connectors` and `space`. You can test out these changes before the next version release by grabbing the required files from the [develop/compiled](https://github.com/fooplugins/FooTable/tree/develop/compiled) folder, checking out the latest develop branch and building the project or simply copying the linked function above to your local version.

With the above change there would be no difference to the original Step 4 of the [dropdown filter](https://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html) example except that the `addFilter` method now accepts 3 additional optional parameters, the first being `ignoreCase` seeing as I think it will be the most commonly used.

``` javascript
_onStatusDropdownChanged: function(e){
    var self = e.data.self, // get the MyFiltering object
        selected = $(this).val(); // get the current dropdown value
    if (selected !== self.def){ // if it's not the default value add a new filter
        self.addFilter('status', selected, ['status'], false); // the new 4th parameter is ignoreCase
    } else { // otherwise remove the filter
        self.removeFilter('status');
    }
    // initiate the actual filter operation
    self.filter();
}
```
