### ISSUE TITLE
No columns supplied Error (v3)

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#507]
Hello,

I have a table with 5 columns that should never hide (based on screen size). But that can be filtered and can be sorted. Since I do not add any breakpoints, FT will fail with the "No columns supplied" error. It looks like this has been talked about here in the past, but I wanted to bring it up again. Why do I have to add in a breakpoint declaration that is blank (data-breakpoints="") just to get around this? Though this is not a very big deal, it does require that I add a little bit of clutter my HTML just to get around this. Just wondering.

Thanks.

**Comment by steveush** [comment]
Hi Jeff,

I'll look at removing this for the next version so you could supply no `data-breakpoints` attributes. At the moment at least one column needs the breakpoint as this was what I thought the main feature of FooTable was, the collapsible details display, however as it has progressed I can see now that this is not 100% correct.

Thanks

**Comment by jeffconklin** [comment]
You sir, are my Footable hero.

Keep up the good work.

**Comment by steveush** [comment]
Hi Jeff,

After looking into this a bit further there is actually a way to get around this built into FooTable at the moment. Basically when parsing a table for columns FooTable needs to figure out which row is the header row so it knows what cells to parse for data attributes. It does this by checking the table for a row using the following selectors, in order:
1. `tr.footable-header`
2. `thead > tr:last:has([data-breakpoints])`
3. `tbody > tr:first:has([data-breakpoints])`

So to get around your issue you can add the `footable-header` class to the row and everything will work. Instead of having to do that though I've added in the below additional selectors as well so FooTable will fall back to using either:
1. `thead > tr:last`
2. `tbody > tr:first`

This way you shouldn't have to define anything unless for some reason FooTable can't find your header automatically.

This will be included in the next version or if you like check out and build the main branch.

Thanks
