### ISSUE TITLE
custom_formatter vs Column Type HTML (v3)

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#509]
Hello,

Within issue #508 , @steveush mentioned that using custom_formatter along with the number data type. This was to aid in formatting and sorting, instead of using the HTML type and sort value. I would like to know which is more efficient.

I have never used custom_formatter, but instead use type HTML and sort values in the same way that is displayed in the first example in #508 . Specifically, I have a few pages that have complex HTML in one or two cells (mainly bootstrap dropdown menus or links). Some have filtering and sorting connected to these columns as well.

I would assume the best practice is to not allow the HTML to be very complex to start. But there are times where a mess can happen. When they do, which approach is better?

A) data-type="number" columns along with using custom_formatter to create the HTML/look you desire.
B) data-type="html" columns and data-sort-value="123" cell, where the HTML in the cell controls the look.

Also, how is sorting and filtering improved / effected by using either.

Thanks.

**Comment by steveush** [comment]
Hi Jeff,

This is a complex question, I've swayed from A to B and back again a few times now while thinking about it and I can't give you a clear cut answer on which would be more efficient. I think they would actually be fairly close in most situations due to how FooTable loads and caches values during initialization so it is primarily working with objects and properties.

What I can say is that using the `formatter` is how I initially intended for people to create HTML in columns but after a few logged issues I thought that it was too low level for the general user and I put together the `data-type="html"` column to make things simpler.

Personally I would try and use the column type that matches my value and then use the `formatter` to generate the HTML for the cells. This way you don't have to output all the extra HTML in the initial page request. If you like you can also make use of a template engine like Mustache or the like to generate the cell content to make managing it a bit easier.

As for effecting filtering or sorting there should be no difference as at that point FooTable is working with objects and properties.

Thanks
