### ISSUE TITLE
How to redraw the footable after the row object array is updated.

### ISSUE THREAD

**Issue by hungchai** [fooplugins/FooTable#511]
I am using Meteor + footable v3, 
As the JS object will be updated automatically by Meteor, 
How does the footable v3 trigger the "redraw" action?  
Moreover , how to get the "currentRow" values in data-formatter function?
Thanks

**Comment by steveush** [comment]
Hi @hungchai,

I'm not sure exactly how you would do this with Meteor as I've never used the framework myself. That said even if the underlying JS object that you used as row data for FooTable is updated/modified the changes will not automatically be seen within FooTable itself. The reason being is that FooTable takes the initial raw row or column data supplied and parses it into `FooTable.Row` or `FooTable.Column` objects which it then works with. To update the table with new data you have to do one of two things;
- Reinitialize the table using the constructor methods (this requires resupplying all the original options).

``` javascript
$('#table').footable({ /* Your Options */ });

// or

FooTable.init('#table', { /* Your Options */ });
```
- Use the [`FooTable.Rows#load()`](https://github.com/fooplugins/FooTable/blob/V3/src/js/components/rows/FooTable.Rows.js#L232) method to simply load just new row data. (In the below the `ft` variable is an instance of FooTable)

``` javascript
ft.rows.load({/* row data */});

// or use the shortcut method

ft.loadRows({/* row data */});
```

As for retrieving the current row within the formatter function, at present this is not possible due to when the function is executed. I would need to look into this a bit further but the main issue I see with trying to access the row is that on first initialization some values may not be parsed yet. The plugin loops through each row and then for each cell calls the `parser` and `formatter` functions one after the other. Which means if you tried to access the row data from the first cell's formatter function then the values for all cells after that may not be parsed or what is expected. For example a date supplied as a string or the ticks value in the second cell will not be available as a moment.js object the first time, it would appear as just the string or tick value, but then the second time around it would be supplied as the moment.js object as it has been previously parsed and cached.

Thanks

**Comment by hungchai** [comment]
Thanks for you tips to reload new row data. Please include them into the document when you have time.

I don't need the parsed values of current row. The best way is to provide the current JS object or a row index in formatter so that I can use them to build a html cell which includes rich contents. For example, I would like have a column to display image, title and Item Id together. And I guess it may not possible if the data loaded from static table.

**Comment by hungchai** [comment]
#513
