### ISSUE TITLE
Footable not working without class

### ISSUE THREAD

**Issue by SLemming** [fooplugins/FooTable#532]
If the table element doesn't has a class, line 2007 breaks with:
`jQuery.Deferred exception: Cannot read property 'match' of undefined TypeError: Cannot read property 'match' of undefined`
That's because the line
`var classes = self.$el.attr('class').match(/\S+/g);`
doesn't check if there are classes available before trying "match"

**Comment by jeffconklin** [comment]
Interesting catch. It is rare that i do not have a class on my tables since I use Bootstrap. But I did just test to see what happens without a class and do receive an error...

`TypeError: self.$el.attr(...) is undefined`
![screenshot from 2016-09-30 16 32 13](https://cloud.githubusercontent.com/assets/6152325/19006062/cfef99ca-872b-11e6-8aee-29edf87d77a9.png)

Example: http://jsbin.com/tixota/edit?html,output

This error is different from what you reported, but seems certainly shows up after I remove the class attribute.
