### ISSUE TITLE
Filter dropdown

### ISSUE THREAD

**Issue by a-naslund** [fooplugins/FooTable#560]
Hi, I'm following the sample on how to add a custom filter dropdown and that works great but how do I do if I want to add another dropdown for another column value? 
FooTable.MyImpact = FooTable.Filtering.extend({....
FooTable.MySev = FooTable.Filtering.extend({....

I've tried to create a second function similar to the first one but it seams I can only register one of them using the global component even if I use different names for each of the filters and it's always the last one that shows even if I switch the order.
FooTable.components.register('filtering', FooTable.MyImpact);
FooTable.components.register('filtering', FooTable.MySev);

**Comment by steveush** [comment]
Hi,

When you create a custom filter drop down you replace the built in `filtering` component when you register  your own. At the moment what is happening is you are replacing your first custom component (`FooTable.MyImpact`) with the second one (`FooTable.MySev`). There can only ever be a single `filtering` component for each table so you need to move the logic from both of your custom implementations into a single one and then register that.

Thanks

**Comment by a-naslund** [comment]
Since I'm not a javascript developer and mostly work with back end integration it's not so easy to merge these two into one even if that is the only solution. Variables like "this._super();" and "var self = this," makes it harder to understand what to replace. I will however give it a try anyway but if there were some sample of who this could be done I would really appreciate it.

**Comment by steveush** [comment]
Hi,

`var self = this;` is simply holding a reference to the current scope, in most cases in FooTable it's a reference to the current class object such as `FooTable.Filtering` and allows us to access the properties or methods of the current class when within the scope of another function/callback. For example in Step 3 of the example when inside the `$.each` loop `this` refers to the current value being iterated instead of the class, so we use the variable `self` to access it instead.

`this._super()` is a custom method to make inheritance simpler, it's the base class's implementation of the current method you are in. In your case `FooTable.Filtering` is the original class that your `FooTable.MyImpact` and `FooTable.MySev` inherit from. So where ever you see `this._super()` it's just calling the original base class's method so you don't have to re-write that code.

The rest is basically just creating a dropdown with jQuery, so you would just need to do it twice. All the code that is needed is in the original example, it's just doubling up the relevant parts (not the `this._super` calls as you only need to call the base implementation once) to create each dropdown.

So you would need to create two `form-group`'s, each with there own `select` element and each of those have there own changed event handler which actually adds the filters to the internal array. Then in the `draw` method you would just double up the code there to ensure both of your dropdowns are correctly set and that should be it.

The below shows the default example modified to output two dropdowns:

```javascript
FooTable.MyFiltering = FooTable.Filtering.extend({
	construct: function(instance){
		this._super(instance);
		// props for the first dropdown
		this.statuses = ['Active','Disabled','Suspended'];
		this.statusDefault = 'Any Status';
		this.$status = null;
		// props for the second dropdown
		this.jobTitles = ['Geophysicist','High School Librarian','Clown', 'etc. etc.'];
		this.jobTitleDefault = 'Any Job Title';
		this.$jobTitle = null;
	},
	$create: function(){
		this._super();
		var self = this;
		// create the status form group and dropdown
		var $status_form_grp = $('<div/>', {'class': 'form-group'})
			.append($('<label/>', {'class': 'sr-only', text: 'Status'}))
			.prependTo(self.$form);

		self.$status = $('<select/>', { 'class': 'form-control' })
			.on('change', {self: self}, self._onStatusDropdownChanged)
			.append($('<option/>', {text: self.statusDefault}))
			.appendTo($status_form_grp);

		$.each(self.statuses, function(i, status){
			self.$status.append($('<option/>').text(status));
		});

		// create the job title form group and dropdown
		var $job_title_form_grp = $('<div/>', {'class': 'form-group'})
			.append($('<label/>', {'class': 'sr-only', text: 'Job Title'}))
			.prependTo(self.$form);

		self.$jobTitle = $('<select/>', { 'class': 'form-control' })
			.on('change', {self: self}, self._onJobTitleDropdownChanged)
			.append($('<option/>', {text: self.jobTitleDefault}))
			.appendTo($job_title_form_grp);

		$.each(self.jobTitles, function(i, jobTitle){
			self.$jobTitle.append($('<option/>').text(jobTitle));
		});
	},
	_onStatusDropdownChanged: function(e){
		var self = e.data.self,
			selected = $(this).val();
		if (selected !== self.statusDefault){
			self.addFilter('status', selected, ['status']);
		} else {
			self.removeFilter('status');
		}
		self.filter();
	},
	_onJobTitleDropdownChanged: function(e){
		var self = e.data.self,
			selected = $(this).val();
		if (selected !== self.jobTitleDefault){
			self.addFilter('jobTitle', selected, ['jobTitle']);
		} else {
			self.removeFilter('jobTitle');
		}
		self.filter();
	},
	draw: function(){
		this._super();
		// handle the status filter if one is supplied
		var status = this.find('status');
		if (status instanceof FooTable.Filter){
			this.$status.val(status.query.val());
		} else {
			this.$status.val(this.statusDefault);
		}

		// handle the jobTitle filter if one is supplied
		var jobTitle = this.find('jobTitle');
		if (jobTitle instanceof FooTable.Filter){
			this.$jobTitle.val(jobTitle.query.val());
		} else {
			this.$jobTitle.val(this.jobTitleDefault);
		}
	}
});
```

Thanks

**Comment by a-naslund** [comment]
Hi, thank you - works perfect, couldn't have done it without you :-)

**Comment by fitzage** [comment]
This is amazing. I know it's a few years old, but…

It would be really swell if this was added to the initial documentation example. I tried this method, but didn't get something right, so it didn't work. But using your instructions, it worked great.
