### ISSUE TITLE
Dynamic Paging not showing in Foo Table design.

### ISSUE THREAD

**Issue by charanjotsingh** [fooplugins/FooTable#567]
Hi, 

I am using Foo Table (FooTable with row toggler, sorting and pagination) design. I applied Foo table classes/attributes given on my table design and its working perfectly fine but my MVC Model has around 4000 records and its showing only single page pagination. If i comment this line of code  **$('.footable').footable();** then it show dynamic paging but then Foo table behavior stops working. Please help what is the correct way to show dynamic paging using Foo table. Here is my code snippet:

Foo Table Output with Pagination:
![footable](https://cloud.githubusercontent.com/assets/19488214/20967400/4a3d679e-bca5-11e6-819b-3de616488c22.JPG)

Expected Pagination Output:
![expectedtable](https://cloud.githubusercontent.com/assets/19488214/20967422/64924efc-bca5-11e6-9616-cbd701a9b849.JPG)

My code Foo table snippet :
[MyCode_Snippet.txt](https://github.com/fooplugins/FooTable/files/636569/MyCode_Snippet.txt)

**Comment by steveush** [comment]
Hi,

I'm not 100% sure what you are asking here, are you saying FooTable is not producing the correct pagination buttons when initialized on a table with 4000 rows? It's been a while since I've worked with MVC but looking at your code snippet you do not need to provide any of the `tfoot` code. All of that is generated by the plugin itself and truthfully I haven't tested what might happen if you have already created it like you have in your page. So try removing all of the following:

```html
<tfoot>
	<tr>
		<td colspan="7">
			<div class="paging">
				@*Paging Section*@
				@*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount*@

				@Html.PagedListPager(Model, page => Url.Action("Index",
new { page, sortOrder = ViewBag.PrevSort, sortColumn = ViewBag.CurrentsortColumn, currentFilter = ViewBag.CurrentFilter }))
			</div>
		</td>
	</tr>
</tfoot>
```

If you are trying to implement server side paging then I'm afraid FooTable does not support that out of the box and you will need to implement it yourself. One of the reasons FooTable does not support server side interaction is that if you want to perform say server side paging, then generally you would want server side filtering and sorting as well. This means the vast majority of the plugins JS becomes redundant as the logic to perform paging, filtering and sorting would be included in a single query against the database, you would have to include those values otherwise the results would be incorrect. Now once you are performing all the underlying paging, filtering and sorting logic on the server and just dumping the returned page rows to the DOM there's not much left for FooTable to do, it would basically just be swapping some classes on the table. Even the CSS is provided by Bootstrap so when it comes to server side interactions it's probably going to be easier to either roll your own using the Bootstrap table CSS or if you need a more complex setup maybe have a look at DataTables. FooTable in my eyes currently falls somewhere in between rolling your own and implementing something like DataTables, it gives you a quick way to get a decent looking table up and running in a very short period of time.

Thanks
