### ISSUE TITLE
Possible Cross-Site Scripting vulnerability

### ISSUE THREAD

**Issue by peterjurkovic** [fooplugins/FooTable#581]
Please see following example: [jsfiddle.net](https://jsfiddle.net/peterjurkovic/f0dqcc0s/)

Even though that a content is encoded to HTML entities, not sure why, but is back decoded to a HTML. If the content contains JS will executed. Does exist any way how to disable this behavior? It might be quite danger. 

It is just happening for the `"text"` column type. With `"html"` it is ok.

**Comment by steveush** [comment]
Hi @peterjurkovic,

I've been working on this this morning and have figured out why it was happening and the fix. The issue is in the FooTable.Column#parser function. Instead of using jQuery's .text() like it currently does to retrieve the content I've switched it to use .html() instead and everything seems to work as expected. jQuery's .text() method decodes the entities and then when the plugin moves/recreates a cell the value is inserted as HTML causing the inline script to be executed, switching to use .html() preserves the entities and everything goes along fine from there.

I'll be including the fix into the develop branch later today sometime and then releasing a new version of FooTable over the weekend.

Thanks

**Comment by steveush** [comment]
Hi,

This should be resolved in the new version 3.1.4.

Thanks
