### ISSUE TITLE
Custom Filter

### ISSUE THREAD

**Issue by poulnike** [fooplugins/FooTable#590]
I have table

```
...
<td data-value="A" data-filter-value="A">Some text</td>
<td data-value="B" data-filter-value="B">Some ather text</td>
<td data-value="C" data-filter-value="C">Some ather text</td>
...
```
Some code

```
...
filter = $(this).val(); 
filtering.addFilter('status', filter, ['status']);
...
```

If filter = "B" it shows only B. That's good. But how important is to have a filter to show both A and B but no ather? Something like filter = "A AND B"

**Comment by steveush** [comment]
Hi @poulnike,

FooTable supports basic query operators such as AND, you can see more in the docs at http://fooplugins.github.io/FooTable/docs/components/filtering.html#queries-and.

Thanks

**Comment by poulnike** [comment]
thanks for the answer @steveush .
I see this, But I dont undestand how it work. In what place it should be applied
I'm try filter = "A AND B" - no result;

**Comment by steveush** [comment]
Hi @poulnike,

Re-reading what you previously wrote I think you are actually wanting to use the `OR` operator instead of `AND`. Using a query such as `A OR B` will return all rows containing either values. Using `AND` is more restrictive, it will remove rows from the results as you are now checking if each row contains both `A` and `B` which by looking at your small example none do.

To summarize `AND` excludes results while `OR` will expand them instead.

Thanks

**Comment by poulnike** [comment]
@steveush
Sorry, I'm stupid)
Thank You.
