### ISSUE TITLE
decimalSeparator and thousandSeparator

### ISSUE THREAD

**Issue by poulnike** [fooplugins/FooTable#595]
colums
```
...
{"name": "UF_ITOGO", "type": "number", "decimalSeparator": ".", "thousandSeparator": ","}
...
```

json rows
```
[  
   { "UF_ITOGO":"200" },
   { "UF_ITOGO":"10.2" },
   { "UF_ITOGO":"0" },
   { "UF_ITOGO":"1,200"}
]
```

But it is sorted as text https://gyazo.com/9b2f8efa71717fbb8082dbfacf77cc74

Without "." and ",", but with quotes ( { "UF_ITOGO":"1200"}) also as text.
Without quotes  in rows json  - work. But I can't use "," for thousand separator

Code: https://jsfiddle.net/poulnike/Lso7p8u6/

**Comment by poulnike** [comment]
Hi @steveush 

I have not found a solution to my problem. If I understand correctly, if value in the json in quotes { "name": "value"} then the "type": "number" does not work. Prompt how to solve this issue.

**Comment by steveush** [comment]
@poulnike this has been fixed in the develop branch of the plugin and will be included in the next release. If you want to test it and use it now you can either checkout and build the develop branch or use the files in the [compiled folder](https://github.com/fooplugins/FooTable/tree/develop/compiled).
