### ISSUE TITLE
Column data-type="number" doesn't work with negative number

### ISSUE THREAD

**Issue by numayos** [fooplugins/FooTable#621]
If the content is negative number ex: -1,  it's transformed to positive number ex:1.

We can't use négative number with this attribute.

**Comment by steveush** [comment]
Hi,

I've replicated this and can confirm it happens only when parsing values from the DOM and not when supplied by the rows option. The issue lies in a regex used to clean the cells text before parsing, basically it's stripping out the `-`.

The below is a quick fix that you can use now by including it in your page after the footable.js file but before you initialize the plugin.

```javascript
(function(F){

	F.NumberColumn.extend("construct", function(instance, definition){
		this._super(instance, definition);
		this.cleanRegex = new RegExp('[^\-0-9' + F.str.escapeRegExp(this.decimalSeparator) + ']', 'g');
	});

})(FooTable);
```

I've pushed this fix to the develop branch and it will be included in the next release. If you want to use the current development version of the plugin instead of using the quick fix you can grab the files you need from out of the [compiled folder](https://github.com/fooplugins/FooTable/tree/develop/compiled).

Thanks

**Comment by numayos** [comment]
Thank you very much. it's perfect.
