### ISSUE TITLE
Row Data vanishes when updating collapsed row - even in Showcase Example

### ISSUE THREAD

**Issue by jonaumann** [fooplugins/FooTable#624]
When I edit a row in the editing component in collapsed mode in the showcase example on the footable website, all the data in the collapsed rows disappear.

Before editing:
![image](https://cloud.githubusercontent.com/assets/24921722/24043005/c52ade10-0b14-11e7-87f0-4ae104fb8504.png)

After editing:
![image](https://cloud.githubusercontent.com/assets/24921722/24043050/ef891b7c-0b14-11e7-98df-537266b3d023.png)

**Comment by steveush** [comment]
Hey @jonaumann,

Thanks for pointing this out. I could replicate the issue using 3.1.4 but not using the develop branch. It seems one of the changes to that branch may have already resolved this problem.

Could you confirm for me the issue is not present when using the development version? You can grab the files you need directly from the [develop branch compiled folder](https://github.com/fooplugins/FooTable/tree/develop/compiled).

Thanks

**Comment by jonaumann** [comment]
Hi @steveush, it works in the development version. Great, thanks!

**Comment by steveush** [comment]
Thanks for confirming, the changes will be included in the next release.
