### ISSUE TITLE
Filtering/sorting not working when type="object" in columns

### ISSUE THREAD

**Issue by mikwebdev** [fooplugins/FooTable#628]
I'm using ajax to get json from a server. The json is nested and therefore I use type="object" to get value from the object data. The formatter function works and I can show the correct value in the table.

I can't get filtering and sorting working for those columns with type="object". 

From my columns:
{"name":"Operator","title":"Company","filterable":true, "breakpoints":"all", "type":"object", "formatter": function (value) { return FooTable.is.object(value) && FooTable.is.string(value.Name) ? value.Name : ''; } },

Do I need to add a function to get filtering/sorting working for type="object" or is there a bug?

Thanks in advance.

**Comment by steveush** [comment]
Hi @mikwebdev,

As it's just an object you need to provide the filter value and sort value so the plugin knows how to perform those operations. There are a few different ways this can be done such as supplying the actual values through the cell options [`sortValue`](http://fooplugins.github.io/FooTable/docs/components/sorting.html#cell-sortValue) and [`filterValue`](http://fooplugins.github.io/FooTable/docs/components/filtering.html#cell-filterValue). However as you are supplying your rows via JSON this would require you to change your JSON structure.

Instead of doing that I would suggest just supplying the column options [`sortValue`](http://fooplugins.github.io/FooTable/docs/components/sorting.html#column-sortValue) and [`filterValue`](http://fooplugins.github.io/FooTable/docs/components/filtering.html#column-filterValue). When supplied as a column option you provide the function used to parse the object and return the value you want to use for that specific operation.

As an example extending on your above code

```javascript
(function($, F){
	
	$(function(){
		$(".table").footable({
			"columns": [{
				"type": "object",
				"formatter": function(value, options, rowData){
					return F.is.object(value) && F.is.string(value.Name) ? value.Name : '';
				},
				"sortValue": function(value){
					return F.is.object(value) && F.is.string(value.Name) ? value.Name : '';
				},
				"filterValue": function(value){
					return F.is.object(value) && F.is.string(value.Name) ? value.Name : '';
				}
			},{
				// other columns
			}],
			// other options
		});
	});
	
})(jQuery, FooTable);
```

However as you're not using the `options` or `rowData` in the `formatter` you could refactor the above to something like the below:

```javascript
(function($, F){
	
	function getObjectValue(obj){
		return F.is.object(obj) && F.is.string(obj.Name) ? obj.Name : '';
	}
	
	$(function(){
		$(".table").footable({
			"columns": [{
				"type": "object",
				"formatter": getObjectValue,
				"sortValue": getObjectValue,
				"filterValue": getObjectValue
			},{
				// other columns
			}],
			// other options
		});
	});
	
})(jQuery, FooTable);
```

Thanks for bringing this up, I'll need to add a bit more info to the docs in the develop branch for the column.

**Comment by mikwebdev** [comment]
Thanks! 
It works! Both filtering and sorting is working as expected now, after applying the code in your first example.

As I'm planning to have labels (Bootstrap component) on text when certain values are equal to set value, I will use a function inside the formatter for the type="object" columns.
