### ISSUE TITLE
Cannot use it whith  the table  that contains 2 rows in tag thead 

### ISSUE THREAD

**Issue by kafele** [fooplugins/FooTable#63]
framework yii generates  table  like below.  When removing  "&lt;tr class="filters"&gt;...&lt;/tr&gt;"  FooTable works, otherwise not.

&lt;table class="footable"&gt;
&lt;thead&gt;
&lt;tr&gt;
&lt;th data-class="expand" id="yw0_c0"&gt;
&lt;a class="sort-link" href="/index.php/payment/admin?Payment_sort=number"&gt;Number&lt;/a&gt;&lt;/th&gt;
&lt;th data-hide="phone" id="yw0_c1"&gt;&lt;a class="sort-link" href="/index.php/payment/admin?Payment_sort=paymentdate"&gt;Paymentdate&lt;/a&gt;&lt;/th&gt;
&lt;th data-hide="phone,tablet" id="yw0_c9"&gt;&nbsp;&lt;/th&gt;
&lt;/tr&gt;

&lt;tr class="filters"&gt;
&lt;td  &gt;&nbsp;&lt;/td&gt;
&lt;td  &gt;&nbsp;&lt;/td&gt;
&lt;td  &gt;&lt;select name="Payment[paymentcurrency]"&gt;
&lt;option value=""&gt;&lt;/option&gt;
&lt;option value="840"&gt;USD&lt;/option&gt;
&lt;option value="643"&gt;RYR&lt;/option&gt;
&lt;/select&gt;&lt;/td&gt;
&lt;/tr&gt;

&lt;/thead&gt;
&lt;tbody&gt;

&lt;tr class="odd"&gt;
&lt;td&gt;43&lt;/td&gt;
&lt;td&gt;18.04.2013&lt;/td&gt;
&lt;td&gt;№   90509&lt;/td&gt;
.....

**Comment by bradvin** [comment]
I can make this configurable via options, something like 

columnDataSelector : '> thead > tr:last-child > th, > thead > tr:last-child > td'

and in your case you can change this to rather be

columnDataSelector : '> thead > tr:first-child > th'

**Comment by bradvin** [comment]
committed : https://github.com/bradvin/FooTable/commit/3625f12e0288b3d793d07f5bbcae2c035edb4c5d

**Comment by thomstark** [comment]
I'm trying to do this. I put several `<tr><td>etc.</tr>` rows in my `<thead>`, after the initial `<tr><th>etc.</tr>` row by which I want to sort, and then I configured the setting like so: 
`columnDataSelector: '> thead > tr:first-child > th',`

But the sort icons disappear from the top table row (the only `th` set), and it actually sorts if you click on the last-child `<thead><tr><td>` row. Is there something I'm missing? See in the screenshot (the `<tr><td>` rows in the `thead` are obvious because they're not styled yet.) 
![theadscreenshot](https://cloud.githubusercontent.com/assets/5798243/4301803/1a097554-3e53-11e4-8ea6-7763928a91e1.jpg)
