### ISSUE TITLE
footable on nested repeater adds comma in textbox

### ISSUE THREAD

**Issue by mkashif130** [fooplugins/FooTable#64]
I have a repeater inside a repeater (that is nested repeater) and applied foo table on it. problem is , when foo table is applied on the repeater (that is , when it is in tablet or cell phone format) a comma is added in textbox. eg: if I enter "empty" in textbox it shows as ",empty" . if i remove ",empty" and add "empty1" then it will show ",empty1,emtpy" in textbox. when i open the page in desktop or laptop view no commas are inserted , even if they are inserted in tablet and cell phone view on resizing them to desktop commas disappear. It is because of footable . tried a lot but didnot find the solution. Any idea?

**Comment by bradvin** [comment]
Please can you post an example of this issue on codepen of jsfilddle

**Comment by mkashif130** [comment]
Thanks bradvin for taking some time out for the issue.

This is what I entered when foo table is applied.
![image](https://f.cloud.github.com/assets/4223753/412834/a5785b2a-abd1-11e2-99bf-f43cc6cc8d9f.png)

This is what it becomes after hitting save button:
![image](https://f.cloud.github.com/assets/4223753/412836/d3187ab0-abd1-11e2-9847-b0018bdbdf27.png)

This is a sample project I created for you. it is telerik based asp.net  project , you will need visual studio 2010 to run it , I don't know if you can manage to run it or not. but I don;t know how to use fiddler for asp.net and telerik. 

http://wikisend.com/download/118354/Test.rar

link will expire in 7 days.

**Comment by bradvin** [comment]
Thanks for posting the project - I got it running and saw what the issue is. When the footable creates the detail row, it duplicates the contents of the cells. So in your example it duplicates the inputs. Your asp.net site works off unique names for each control, so the values gets passed back to the form as a comma separated list (because there are 2 controls with the same name) and a comma is inserted.

You either need to handle the ajax call manually and not rely on the asp.net postback system via the telerik ajax handler, or you need to intercept when footable is creating the detail row.

I will add some code to raise an event when the detail row is created. I will comment here once I have done that

**Comment by mkashif130** [comment]
Thanks , your help will be highly appreciated.

**Comment by bradvin** [comment]
there is now a new event raised when creating or updating the detail row : https://github.com/bradvin/FooTable/commit/b35da00ac0b0a1f6509a85cfc668d86d47826e75

You will still need to be quite clever how you do this to get it working. I was thinking perhaps appending "_hidden" to the name and id of the inputs when they are created in the detail row, and removing the "_hidden" when the breakpoint is not hit and then appending _hidden to the inputs in the detail row
