### ISSUE TITLE
Footable-details table copy classes from main table

### ISSUE THREAD

**Issue by poulnike** [fooplugins/FooTable#643]
Footable-details table copy classes from main table
Can I avoid this?

Otherwise, I have to redefine all classes for footable-details by multiplying cascades, and this is not entirely true.

**Comment by steveush** [comment]
Hi @poulnike,

There is no option to disable this but you can override the [`FooTable.Row#$create`](https://github.com/fooplugins/FooTable/blob/V3/src/js/classes/FooTable.Row.js#L113) method with your own and stop it applying the classes all together. The original intention for the copying was so that classes such as Bootstrap's `table-bordered`, `table-striped`, etc. we duplicated across so the details tables match the actual table. The below should do what you are wanting:

```javascript
(function($, F){

	F.Row.extend("$create", function(){
		if (this.created) return;
		(this.$el = F.is.jq(this.$el) ? this.$el : $('<tr/>'))
			.data('__FooTableRow__', this);

		this._setClasses(this.$el);
		this._setStyle(this.$el);

		if (this.ft.rows.toggleColumn == 'last') this.$toggle.addClass('last-column');

		this.$details = $('<tr/>', { 'class': 'footable-detail-row' })
			.append($('<td/>', { colspan: this.ft.columns.visibleColspan })
				.append($('<table/>', { 'class': 'footable-details' })
					.append('<tbody/>')));

		var self = this;
		F.arr.each(self.cells, function(cell){
			if (!cell.created) cell.$create();
			self.$el.append(cell.$el);
		});
		self.$el.off('click.ft.row').on('click.ft.row', { self: self }, self._onToggle);
		this.created = true;
	});

})(jQuery, FooTable);
```

The above just needs to be included in your page after the plugin files but before you initialize any instances.

Thanks
