### ISSUE TITLE
load columns data dynamically after the initialization of footable

### ISSUE THREAD

**Issue by prashant-pokhriyal** [fooplugins/FooTable#661]
After initialization of footable with default column content I want to change column content on user selection without initializing footable again.

Actually I'm looking for similar function we have for loading row --------> `ft.rows.load(data)`
Something like this ---> `ft.columns.load(data)`

**Comment by prashant-pokhriyal** [comment]
Is there any active maintainer? @steveush

**Comment by steveush** [comment]
Hi,

Sorry, I'm currently on a push on another project and don't have time at the moment to make updates to FooTable. Once this final push on the other project is done I'll be able to dedicate some time to fixing issues and releasing the next version.

As for your question, currently there is no way to switch out columns on the fly as they are at the core of the plugin and how it functions. The rows, cells and other components such as sorting etc. all rely on the columns being known at the time they are initialized and they take certain actions depending on them. Due to this the only way to change the columns is currently to reinitialize the plugin with the new column options.

Thanks
